import 'controller/fortytwo_controller.dart';import 'package:faz/core/app_export.dart';import 'package:faz/widgets/app_bar/appbar_leading_image.dart';import 'package:faz/widgets/app_bar/appbar_title.dart';import 'package:faz/widgets/app_bar/custom_app_bar.dart';import 'package:faz/widgets/custom_drop_down.dart';import 'package:faz/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class FortytwoScreen extends GetWidget<FortytwoController> {const FortytwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 10.h), child: Column(children: [SizedBox(height: 10.v), _buildTamilnaduCable(), SizedBox(height: 33.v), Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomDropDown(hintText: "lbl_district".tr, items: controller.fortytwoModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.outlineBlack, filled: true, fillColor: appTheme.gray900, onChanged: (value) {controller.onSelected(value);})), SizedBox(height: 24.v), Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: CustomDropDown(hintText: "lbl_village".tr, items: controller.fortytwoModelObj.value.dropdownItemList1!.value, borderDecoration: DropDownStyleHelper.outlineBlack, filled: true, fillColor: appTheme.gray900, onChanged: (value) {controller.onSelected1(value);})), SizedBox(height: 27.v), _buildDno1(), SizedBox(height: 27.v), _buildFlatno1(), SizedBox(height: 34.v), GestureDetector(onTap: () {onTapFrame();}, child: Container(height: 53.v, width: 126.h, padding: EdgeInsets.symmetric(horizontal: 35.h, vertical: 19.v), decoration: AppDecoration.fillDeepPurpleA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgSettings, height: 13.v, width: 56.h, alignment: Alignment.center)))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 67.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgBack, margin: EdgeInsets.only(left: 35.h, top: 22.v, bottom: 22.v), onTap: () {onTapBack();}), title: AppbarTitle(text: "lbl_cable2".tr, margin: EdgeInsets.only(left: 25.h)), styleType: Style.bgFill_1); } 
/// Section Widget
Widget _buildTamilnaduCable() { return SizedBox(height: 242.v, width: 334.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(left: 3.h, right: 2.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 7.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgEllipse7735x35, height: 35.adaptSize, width: 35.adaptSize, radius: BorderRadius.circular(17.h), margin: EdgeInsets.only(top: 193.v)), Padding(padding: EdgeInsets.only(left: 18.h, top: 201.v, bottom: 8.v), child: Text("msg_tamilnadu_cable".tr, style: theme.textTheme.labelLarge))]))), CustomImageView(imagePath: ImageConstant.imgRectangle1064, height: 190.v, width: 334.h, radius: BorderRadius.circular(6.h), alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 1.v))])); } 
/// Section Widget
Widget _buildDno() { return CustomTextFormField(width: 130.h, controller: controller.dnoController, hintText: "lbl_d_no".tr, hintStyle: theme.textTheme.bodyLarge!); } 
/// Section Widget
Widget _buildBillno() { return Padding(padding: EdgeInsets.only(left: 12.h), child: CustomTextFormField(width: 130.h, controller: controller.billnoController, hintText: "lbl_bill_no".tr, hintStyle: theme.textTheme.bodyLarge!)); } 
/// Section Widget
Widget _buildDno1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildDno(), _buildBillno()])); } 
/// Section Widget
Widget _buildFlatno() { return CustomTextFormField(width: 130.h, controller: controller.flatnoController, hintText: "lbl_flat_no".tr, hintStyle: theme.textTheme.bodyLarge!); } 
/// Section Widget
Widget _buildSeno() { return Padding(padding: EdgeInsets.only(left: 12.h), child: CustomTextFormField(width: 130.h, controller: controller.senoController, hintText: "lbl_se_no".tr, hintStyle: theme.textTheme.bodyLarge!, textInputAction: TextInputAction.done)); } 
/// Section Widget
Widget _buildFlatno1() { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildFlatno(), _buildSeno()])); } 
/// Navigates to the fortyoneScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.fortyoneScreen, ); } 
/// Navigates to the fortythreeScreen when the action is triggered.
onTapFrame() { Get.toNamed(AppRoutes.fortythreeScreen, ); } 
 }
