// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfDdie6KvgduLaFCtyf_vKJkKuHSZeC8',
    appId: '1:996360374964:web:3d4742d262ef8bc62025e1',
    messagingSenderId: '996360374964',
    projectId: 'recharge-app-d0e3a',
    authDomain: 'recharge-app-d0e3a.firebaseapp.com',
    storageBucket: 'recharge-app-d0e3a.appspot.com',
    measurementId: 'G-LZM725X7NB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJVHPKplPCnG-tXpQse6B8k5nJGxnQSM',
    appId: '1:996360374964:android:29d571e19264474a2025e1',
    messagingSenderId: '996360374964',
    projectId: 'recharge-app-d0e3a',
    storageBucket: 'recharge-app-d0e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUcNe-0xiLchp_PLVLY_kQ4nsl1R7cRYk',
    appId: '1:996360374964:ios:4ae09557c43a23792025e1',
    messagingSenderId: '996360374964',
    projectId: 'recharge-app-d0e3a',
    storageBucket: 'recharge-app-d0e3a.appspot.com',
    iosBundleId: 'com.faz.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUcNe-0xiLchp_PLVLY_kQ4nsl1R7cRYk',
    appId: '1:996360374964:ios:fb6ff9a8540470892025e1',
    messagingSenderId: '996360374964',
    projectId: 'recharge-app-d0e3a',
    storageBucket: 'recharge-app-d0e3a.appspot.com',
    iosBundleId: 'com.faz.faz.RunnerTests',
  );
}
