import 'controller/thirty_controller.dart';import 'package:faz/core/app_export.dart';import 'package:faz/widgets/app_bar/appbar_leading_image.dart';import 'package:faz/widgets/app_bar/appbar_title.dart';import 'package:faz/widgets/app_bar/custom_app_bar.dart';import 'package:faz/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class ThirtyScreen extends GetWidget<ThirtyController> {const ThirtyScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Container(margin: EdgeInsets.only(bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 10.h), child: Column(children: [SizedBox(height: 60.v), CustomImageView(imagePath: ImageConstant.imgRectangle1064, height: 173.v, width: 334.h, radius: BorderRadius.circular(6.h)), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(left: 20.h, right: 21.h), child: CustomSearchView(controller: controller.searchController, hintText: "lbl_search".tr)), SizedBox(height: 12.v), CustomImageView(imagePath: ImageConstant.imgFrame33653, height: 159.v, width: 337.h, radius: BorderRadius.circular(8.h)), SizedBox(height: 17.v), _buildFrame()])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 67.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgBack, margin: EdgeInsets.only(left: 35.h, top: 22.v, bottom: 22.v), onTap: () {onTapBack();}), title: AppbarTitle(text: "lbl_dth".tr, margin: EdgeInsets.only(left: 24.h)), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildFrame() { return Container(width: 337.h, margin: EdgeInsets.symmetric(horizontal: 19.h), padding: EdgeInsets.symmetric(horizontal: 36.h), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 26.v), Text("lbl_dth".tr, style: CustomTextStyles.titleMediumGray60004), SizedBox(height: 29.v), _buildDianiRow1(titleText: "msg_airtel_digital_tv".tr), SizedBox(height: 30.v), _buildDianiRow2(channelName: "msg_colors_rishtey_tv".tr), SizedBox(height: 30.v), _buildDianiRow1(titleText: "msg_airtel_digital_tv".tr), SizedBox(height: 76.v), _buildDianiRow2(channelName: "msg_colors_rishtey_tv".tr), SizedBox(height: 141.v), _buildDianiRow1(titleText: "msg_airtel_digital_tv".tr), SizedBox(height: 206.v), _buildDianiRow2(channelName: "msg_colors_rishtey_tv".tr)])); } 
/// Common widget
Widget _buildDianiRow1({required String titleText}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse771, height: 35.adaptSize, width: 35.adaptSize, radius: BorderRadius.circular(17.h)), Padding(padding: EdgeInsets.only(left: 18.h, top: 9.v), child: Text(titleText, style: CustomTextStyles.labelLargeBlack900.copyWith(color: appTheme.black900)))]); } 
/// Common widget
Widget _buildDianiRow2({required String channelName}) { return Row(children: [CustomImageView(imagePath: ImageConstant.imgEllipse772, height: 35.adaptSize, width: 35.adaptSize, radius: BorderRadius.circular(17.h)), Padding(padding: EdgeInsets.only(left: 18.h, top: 9.v), child: Text(channelName, style: CustomTextStyles.labelLargeBlack900.copyWith(color: appTheme.black900)))]); } 
/// Navigates to the eightScreen when the action is triggered.
onTapBack() { Get.toNamed(AppRoutes.eightScreen, ); } 
/// Navigates to the thirtyoneScreen when the action is triggered.
onTapDianiRow1() { Get.toNamed(AppRoutes.thirtyoneScreen, ); } 
 }
